### ISSUE TITLE
Initialize ctor from properties is being put before the namespace import 

### ISSUE THREAD

**Issue by tugberkugurlu** [jchannon/csharpextensions#13]
![image](https://cloud.githubusercontent.com/assets/328122/20809612/8473eee8-b7fe-11e6-8cd9-252a33bdc49a.png)

which is not ideal I think. Would be nice to have it come after them if possible.

**Comment by jchannon** [comment]
Agree. Wonder if it's the order in which extensions are registered. Wonder
if @simsod knows

**Comment by simsod** [comment]
@jchannon I think I saw something somewhere in the docs about the order of codeactions, i´ll have a look at it.

**Comment by simsod** [comment]
I haven´t been able to find any information about how the order of the commands are sorted.
Since it´s a promise you return from the provideCodeActions method I´m guessing it´s just in the order that the promises are returned.
I guess we could do a setTimeout to make the codeActions return slower than omnisharp-vscode  delivers theirs, but that seems really really ugly.
